// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package raven

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *BodyType) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 string
		zb0001, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = BodyType(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z BodyType) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteString(string(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z BodyType) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendString(o, string(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *BodyType) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 string
		zb0001, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = BodyType(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z BodyType) Msgsize() (s int) {
	s = msgp.StringPrefixSize + len(string(z))
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Content) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Headers":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Headers")
				return
			}
			if cap(z.Headers) >= int(zb0002) {
				z.Headers = (z.Headers)[:zb0002]
			} else {
				z.Headers = make(Headers, zb0002)
			}
			for za0001 := range z.Headers {
				var zb0003 uint32
				zb0003, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "Headers", za0001)
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "Headers", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "Name":
						z.Headers[za0001].Name, err = dc.ReadString()
						if err != nil {
							err = msgp.WrapError(err, "Headers", za0001, "Name")
							return
						}
					case "Value":
						z.Headers[za0001].Value, err = dc.ReadString()
						if err != nil {
							err = msgp.WrapError(err, "Headers", za0001, "Value")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "Headers", za0001)
							return
						}
					}
				}
			}
		case "Body":
			z.Body, err = dc.ReadBytes(z.Body)
			if err != nil {
				err = msgp.WrapError(err, "Body")
				return
			}
		case "Encoding":
			err = z.Encoding.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Encoding")
				return
			}
		case "Charset":
			z.Charset, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Charset")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Content) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "Headers"
	err = en.Append(0x84, 0xa7, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Headers)))
	if err != nil {
		err = msgp.WrapError(err, "Headers")
		return
	}
	for za0001 := range z.Headers {
		// map header, size 2
		// write "Name"
		err = en.Append(0x82, 0xa4, 0x4e, 0x61, 0x6d, 0x65)
		if err != nil {
			return
		}
		err = en.WriteString(z.Headers[za0001].Name)
		if err != nil {
			err = msgp.WrapError(err, "Headers", za0001, "Name")
			return
		}
		// write "Value"
		err = en.Append(0xa5, 0x56, 0x61, 0x6c, 0x75, 0x65)
		if err != nil {
			return
		}
		err = en.WriteString(z.Headers[za0001].Value)
		if err != nil {
			err = msgp.WrapError(err, "Headers", za0001, "Value")
			return
		}
	}
	// write "Body"
	err = en.Append(0xa4, 0x42, 0x6f, 0x64, 0x79)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Body)
	if err != nil {
		err = msgp.WrapError(err, "Body")
		return
	}
	// write "Encoding"
	err = en.Append(0xa8, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67)
	if err != nil {
		return
	}
	err = z.Encoding.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Encoding")
		return
	}
	// write "Charset"
	err = en.Append(0xa7, 0x43, 0x68, 0x61, 0x72, 0x73, 0x65, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Charset)
	if err != nil {
		err = msgp.WrapError(err, "Charset")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Content) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "Headers"
	o = append(o, 0x84, 0xa7, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Headers)))
	for za0001 := range z.Headers {
		// map header, size 2
		// string "Name"
		o = append(o, 0x82, 0xa4, 0x4e, 0x61, 0x6d, 0x65)
		o = msgp.AppendString(o, z.Headers[za0001].Name)
		// string "Value"
		o = append(o, 0xa5, 0x56, 0x61, 0x6c, 0x75, 0x65)
		o = msgp.AppendString(o, z.Headers[za0001].Value)
	}
	// string "Body"
	o = append(o, 0xa4, 0x42, 0x6f, 0x64, 0x79)
	o = msgp.AppendBytes(o, z.Body)
	// string "Encoding"
	o = append(o, 0xa8, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67)
	o, err = z.Encoding.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Encoding")
		return
	}
	// string "Charset"
	o = append(o, 0xa7, 0x43, 0x68, 0x61, 0x72, 0x73, 0x65, 0x74)
	o = msgp.AppendString(o, z.Charset)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Content) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Headers":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Headers")
				return
			}
			if cap(z.Headers) >= int(zb0002) {
				z.Headers = (z.Headers)[:zb0002]
			} else {
				z.Headers = make(Headers, zb0002)
			}
			for za0001 := range z.Headers {
				var zb0003 uint32
				zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Headers", za0001)
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "Headers", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "Name":
						z.Headers[za0001].Name, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Headers", za0001, "Name")
							return
						}
					case "Value":
						z.Headers[za0001].Value, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "Headers", za0001, "Value")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "Headers", za0001)
							return
						}
					}
				}
			}
		case "Body":
			z.Body, bts, err = msgp.ReadBytesBytes(bts, z.Body)
			if err != nil {
				err = msgp.WrapError(err, "Body")
				return
			}
		case "Encoding":
			bts, err = z.Encoding.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Encoding")
				return
			}
		case "Charset":
			z.Charset, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Charset")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Content) Msgsize() (s int) {
	s = 1 + 8 + msgp.ArrayHeaderSize
	for za0001 := range z.Headers {
		s += 1 + 5 + msgp.StringPrefixSize + len(z.Headers[za0001].Name) + 6 + msgp.StringPrefixSize + len(z.Headers[za0001].Value)
	}
	s += 5 + msgp.BytesPrefixSize + len(z.Body) + 9 + z.Encoding.Msgsize() + 8 + msgp.StringPrefixSize + len(z.Charset)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *DSNEnvelopeParams) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "RET":
			z.RET, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "RET")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z DSNEnvelopeParams) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "RET"
	err = en.Append(0x81, 0xa3, 0x52, 0x45, 0x54)
	if err != nil {
		return
	}
	err = en.WriteString(z.RET)
	if err != nil {
		err = msgp.WrapError(err, "RET")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z DSNEnvelopeParams) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	// string "RET"
	o = append(o, 0x81, 0xa3, 0x52, 0x45, 0x54)
	o = msgp.AppendString(o, z.RET)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *DSNEnvelopeParams) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "RET":
			z.RET, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "RET")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z DSNEnvelopeParams) Msgsize() (s int) {
	s = 1 + 4 + msgp.StringPrefixSize + len(z.RET)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *DSNRecipientParams) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Notify":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Notify")
				return
			}
			if cap(z.Notify) >= int(zb0002) {
				z.Notify = (z.Notify)[:zb0002]
			} else {
				z.Notify = make([]string, zb0002)
			}
			for za0001 := range z.Notify {
				z.Notify[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Notify", za0001)
					return
				}
			}
		case "ORcpt":
			z.ORcpt, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ORcpt")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *DSNRecipientParams) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "Notify"
	err = en.Append(0x82, 0xa6, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Notify)))
	if err != nil {
		err = msgp.WrapError(err, "Notify")
		return
	}
	for za0001 := range z.Notify {
		err = en.WriteString(z.Notify[za0001])
		if err != nil {
			err = msgp.WrapError(err, "Notify", za0001)
			return
		}
	}
	// write "ORcpt"
	err = en.Append(0xa5, 0x4f, 0x52, 0x63, 0x70, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.ORcpt)
	if err != nil {
		err = msgp.WrapError(err, "ORcpt")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *DSNRecipientParams) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "Notify"
	o = append(o, 0x82, 0xa6, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Notify)))
	for za0001 := range z.Notify {
		o = msgp.AppendString(o, z.Notify[za0001])
	}
	// string "ORcpt"
	o = append(o, 0xa5, 0x4f, 0x52, 0x63, 0x70, 0x74)
	o = msgp.AppendString(o, z.ORcpt)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *DSNRecipientParams) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Notify":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Notify")
				return
			}
			if cap(z.Notify) >= int(zb0002) {
				z.Notify = (z.Notify)[:zb0002]
			} else {
				z.Notify = make([]string, zb0002)
			}
			for za0001 := range z.Notify {
				z.Notify[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Notify", za0001)
					return
				}
			}
		case "ORcpt":
			z.ORcpt, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ORcpt")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *DSNRecipientParams) Msgsize() (s int) {
	s = 1 + 7 + msgp.ArrayHeaderSize
	for za0001 := range z.Notify {
		s += msgp.StringPrefixSize + len(z.Notify[za0001])
	}
	s += 6 + msgp.StringPrefixSize + len(z.ORcpt)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Envelope) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "From":
			err = z.From.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "From")
				return
			}
		case "To":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "To")
				return
			}
			if cap(z.To) >= int(zb0002) {
				z.To = (z.To)[:zb0002]
			} else {
				z.To = make([]Recipient, zb0002)
			}
			for za0001 := range z.To {
				err = z.To[za0001].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "To", za0001)
					return
				}
			}
		case "BodyType":
			{
				var zb0003 string
				zb0003, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "BodyType")
					return
				}
				z.BodyType = BodyType(zb0003)
			}
		case "Size":
			z.Size, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Size")
				return
			}
		case "SMTPUTF8":
			z.SMTPUTF8, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "SMTPUTF8")
				return
			}
		case "RequireTLS":
			z.RequireTLS, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "RequireTLS")
				return
			}
		case "EnvID":
			z.EnvID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "EnvID")
				return
			}
		case "DSNParams":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "DSNParams")
					return
				}
				z.DSNParams = nil
			} else {
				if z.DSNParams == nil {
					z.DSNParams = new(DSNEnvelopeParams)
				}
				var zb0004 uint32
				zb0004, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "DSNParams")
					return
				}
				for zb0004 > 0 {
					zb0004--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "DSNParams")
						return
					}
					switch msgp.UnsafeString(field) {
					case "RET":
						z.DSNParams.RET, err = dc.ReadString()
						if err != nil {
							err = msgp.WrapError(err, "DSNParams", "RET")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "DSNParams")
							return
						}
					}
				}
			}
		case "Auth":
			z.Auth, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Auth")
				return
			}
		case "ExtensionParams":
			var zb0005 uint32
			zb0005, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "ExtensionParams")
				return
			}
			if z.ExtensionParams == nil {
				z.ExtensionParams = make(map[string]string, zb0005)
			} else if len(z.ExtensionParams) > 0 {
				clear(z.ExtensionParams)
			}
			for zb0005 > 0 {
				zb0005--
				var za0002 string
				za0002, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "ExtensionParams")
					return
				}
				var za0003 string
				za0003, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "ExtensionParams", za0002)
					return
				}
				z.ExtensionParams[za0002] = za0003
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Envelope) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 10
	// write "From"
	err = en.Append(0x8a, 0xa4, 0x46, 0x72, 0x6f, 0x6d)
	if err != nil {
		return
	}
	err = z.From.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "From")
		return
	}
	// write "To"
	err = en.Append(0xa2, 0x54, 0x6f)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.To)))
	if err != nil {
		err = msgp.WrapError(err, "To")
		return
	}
	for za0001 := range z.To {
		err = z.To[za0001].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "To", za0001)
			return
		}
	}
	// write "BodyType"
	err = en.Append(0xa8, 0x42, 0x6f, 0x64, 0x79, 0x54, 0x79, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(string(z.BodyType))
	if err != nil {
		err = msgp.WrapError(err, "BodyType")
		return
	}
	// write "Size"
	err = en.Append(0xa4, 0x53, 0x69, 0x7a, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Size)
	if err != nil {
		err = msgp.WrapError(err, "Size")
		return
	}
	// write "SMTPUTF8"
	err = en.Append(0xa8, 0x53, 0x4d, 0x54, 0x50, 0x55, 0x54, 0x46, 0x38)
	if err != nil {
		return
	}
	err = en.WriteBool(z.SMTPUTF8)
	if err != nil {
		err = msgp.WrapError(err, "SMTPUTF8")
		return
	}
	// write "RequireTLS"
	err = en.Append(0xaa, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x54, 0x4c, 0x53)
	if err != nil {
		return
	}
	err = en.WriteBool(z.RequireTLS)
	if err != nil {
		err = msgp.WrapError(err, "RequireTLS")
		return
	}
	// write "EnvID"
	err = en.Append(0xa5, 0x45, 0x6e, 0x76, 0x49, 0x44)
	if err != nil {
		return
	}
	err = en.WriteString(z.EnvID)
	if err != nil {
		err = msgp.WrapError(err, "EnvID")
		return
	}
	// write "DSNParams"
	err = en.Append(0xa9, 0x44, 0x53, 0x4e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73)
	if err != nil {
		return
	}
	if z.DSNParams == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		// map header, size 1
		// write "RET"
		err = en.Append(0x81, 0xa3, 0x52, 0x45, 0x54)
		if err != nil {
			return
		}
		err = en.WriteString(z.DSNParams.RET)
		if err != nil {
			err = msgp.WrapError(err, "DSNParams", "RET")
			return
		}
	}
	// write "Auth"
	err = en.Append(0xa4, 0x41, 0x75, 0x74, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.Auth)
	if err != nil {
		err = msgp.WrapError(err, "Auth")
		return
	}
	// write "ExtensionParams"
	err = en.Append(0xaf, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.ExtensionParams)))
	if err != nil {
		err = msgp.WrapError(err, "ExtensionParams")
		return
	}
	for za0002, za0003 := range z.ExtensionParams {
		err = en.WriteString(za0002)
		if err != nil {
			err = msgp.WrapError(err, "ExtensionParams")
			return
		}
		err = en.WriteString(za0003)
		if err != nil {
			err = msgp.WrapError(err, "ExtensionParams", za0002)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Envelope) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 10
	// string "From"
	o = append(o, 0x8a, 0xa4, 0x46, 0x72, 0x6f, 0x6d)
	o, err = z.From.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "From")
		return
	}
	// string "To"
	o = append(o, 0xa2, 0x54, 0x6f)
	o = msgp.AppendArrayHeader(o, uint32(len(z.To)))
	for za0001 := range z.To {
		o, err = z.To[za0001].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "To", za0001)
			return
		}
	}
	// string "BodyType"
	o = append(o, 0xa8, 0x42, 0x6f, 0x64, 0x79, 0x54, 0x79, 0x70, 0x65)
	o = msgp.AppendString(o, string(z.BodyType))
	// string "Size"
	o = append(o, 0xa4, 0x53, 0x69, 0x7a, 0x65)
	o = msgp.AppendInt64(o, z.Size)
	// string "SMTPUTF8"
	o = append(o, 0xa8, 0x53, 0x4d, 0x54, 0x50, 0x55, 0x54, 0x46, 0x38)
	o = msgp.AppendBool(o, z.SMTPUTF8)
	// string "RequireTLS"
	o = append(o, 0xaa, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x54, 0x4c, 0x53)
	o = msgp.AppendBool(o, z.RequireTLS)
	// string "EnvID"
	o = append(o, 0xa5, 0x45, 0x6e, 0x76, 0x49, 0x44)
	o = msgp.AppendString(o, z.EnvID)
	// string "DSNParams"
	o = append(o, 0xa9, 0x44, 0x53, 0x4e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73)
	if z.DSNParams == nil {
		o = msgp.AppendNil(o)
	} else {
		// map header, size 1
		// string "RET"
		o = append(o, 0x81, 0xa3, 0x52, 0x45, 0x54)
		o = msgp.AppendString(o, z.DSNParams.RET)
	}
	// string "Auth"
	o = append(o, 0xa4, 0x41, 0x75, 0x74, 0x68)
	o = msgp.AppendString(o, z.Auth)
	// string "ExtensionParams"
	o = append(o, 0xaf, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73)
	o = msgp.AppendMapHeader(o, uint32(len(z.ExtensionParams)))
	for za0002, za0003 := range z.ExtensionParams {
		o = msgp.AppendString(o, za0002)
		o = msgp.AppendString(o, za0003)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Envelope) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "From":
			bts, err = z.From.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "From")
				return
			}
		case "To":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "To")
				return
			}
			if cap(z.To) >= int(zb0002) {
				z.To = (z.To)[:zb0002]
			} else {
				z.To = make([]Recipient, zb0002)
			}
			for za0001 := range z.To {
				bts, err = z.To[za0001].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "To", za0001)
					return
				}
			}
		case "BodyType":
			{
				var zb0003 string
				zb0003, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "BodyType")
					return
				}
				z.BodyType = BodyType(zb0003)
			}
		case "Size":
			z.Size, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Size")
				return
			}
		case "SMTPUTF8":
			z.SMTPUTF8, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SMTPUTF8")
				return
			}
		case "RequireTLS":
			z.RequireTLS, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "RequireTLS")
				return
			}
		case "EnvID":
			z.EnvID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "EnvID")
				return
			}
		case "DSNParams":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.DSNParams = nil
			} else {
				if z.DSNParams == nil {
					z.DSNParams = new(DSNEnvelopeParams)
				}
				var zb0004 uint32
				zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "DSNParams")
					return
				}
				for zb0004 > 0 {
					zb0004--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "DSNParams")
						return
					}
					switch msgp.UnsafeString(field) {
					case "RET":
						z.DSNParams.RET, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "DSNParams", "RET")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "DSNParams")
							return
						}
					}
				}
			}
		case "Auth":
			z.Auth, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Auth")
				return
			}
		case "ExtensionParams":
			var zb0005 uint32
			zb0005, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ExtensionParams")
				return
			}
			if z.ExtensionParams == nil {
				z.ExtensionParams = make(map[string]string, zb0005)
			} else if len(z.ExtensionParams) > 0 {
				clear(z.ExtensionParams)
			}
			for zb0005 > 0 {
				var za0003 string
				zb0005--
				var za0002 string
				za0002, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ExtensionParams")
					return
				}
				za0003, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ExtensionParams", za0002)
					return
				}
				z.ExtensionParams[za0002] = za0003
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Envelope) Msgsize() (s int) {
	s = 1 + 5 + z.From.Msgsize() + 3 + msgp.ArrayHeaderSize
	for za0001 := range z.To {
		s += z.To[za0001].Msgsize()
	}
	s += 9 + msgp.StringPrefixSize + len(string(z.BodyType)) + 5 + msgp.Int64Size + 9 + msgp.BoolSize + 11 + msgp.BoolSize + 6 + msgp.StringPrefixSize + len(z.EnvID) + 10
	if z.DSNParams == nil {
		s += msgp.NilSize
	} else {
		s += 1 + 4 + msgp.StringPrefixSize + len(z.DSNParams.RET)
	}
	s += 5 + msgp.StringPrefixSize + len(z.Auth) + 16 + msgp.MapHeaderSize
	if z.ExtensionParams != nil {
		for za0002, za0003 := range z.ExtensionParams {
			_ = za0003
			s += msgp.StringPrefixSize + len(za0002) + msgp.StringPrefixSize + len(za0003)
		}
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Header) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Name":
			z.Name, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "Value":
			z.Value, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Value")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Header) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "Name"
	err = en.Append(0x82, 0xa4, 0x4e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Name)
	if err != nil {
		err = msgp.WrapError(err, "Name")
		return
	}
	// write "Value"
	err = en.Append(0xa5, 0x56, 0x61, 0x6c, 0x75, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Value)
	if err != nil {
		err = msgp.WrapError(err, "Value")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Header) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "Name"
	o = append(o, 0x82, 0xa4, 0x4e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Name)
	// string "Value"
	o = append(o, 0xa5, 0x56, 0x61, 0x6c, 0x75, 0x65)
	o = msgp.AppendString(o, z.Value)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Header) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Name":
			z.Name, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Name")
				return
			}
		case "Value":
			z.Value, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Value")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Header) Msgsize() (s int) {
	s = 1 + 5 + msgp.StringPrefixSize + len(z.Name) + 6 + msgp.StringPrefixSize + len(z.Value)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Headers) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0002 uint32
	zb0002, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if cap((*z)) >= int(zb0002) {
		(*z) = (*z)[:zb0002]
	} else {
		(*z) = make(Headers, zb0002)
	}
	for zb0001 := range *z {
		var field []byte
		_ = field
		var zb0003 uint32
		zb0003, err = dc.ReadMapHeader()
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		for zb0003 > 0 {
			zb0003--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				err = msgp.WrapError(err, zb0001)
				return
			}
			switch msgp.UnsafeString(field) {
			case "Name":
				(*z)[zb0001].Name, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, zb0001, "Name")
					return
				}
			case "Value":
				(*z)[zb0001].Value, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, zb0001, "Value")
					return
				}
			default:
				err = dc.Skip()
				if err != nil {
					err = msgp.WrapError(err, zb0001)
					return
				}
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Headers) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteArrayHeader(uint32(len(z)))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0004 := range z {
		// map header, size 2
		// write "Name"
		err = en.Append(0x82, 0xa4, 0x4e, 0x61, 0x6d, 0x65)
		if err != nil {
			return
		}
		err = en.WriteString(z[zb0004].Name)
		if err != nil {
			err = msgp.WrapError(err, zb0004, "Name")
			return
		}
		// write "Value"
		err = en.Append(0xa5, 0x56, 0x61, 0x6c, 0x75, 0x65)
		if err != nil {
			return
		}
		err = en.WriteString(z[zb0004].Value)
		if err != nil {
			err = msgp.WrapError(err, zb0004, "Value")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z Headers) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendArrayHeader(o, uint32(len(z)))
	for zb0004 := range z {
		// map header, size 2
		// string "Name"
		o = append(o, 0x82, 0xa4, 0x4e, 0x61, 0x6d, 0x65)
		o = msgp.AppendString(o, z[zb0004].Name)
		// string "Value"
		o = append(o, 0xa5, 0x56, 0x61, 0x6c, 0x75, 0x65)
		o = msgp.AppendString(o, z[zb0004].Value)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Headers) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0002 uint32
	zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if cap((*z)) >= int(zb0002) {
		(*z) = (*z)[:zb0002]
	} else {
		(*z) = make(Headers, zb0002)
	}
	for zb0001 := range *z {
		var field []byte
		_ = field
		var zb0003 uint32
		zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		for zb0003 > 0 {
			zb0003--
			field, bts, err = msgp.ReadMapKeyZC(bts)
			if err != nil {
				err = msgp.WrapError(err, zb0001)
				return
			}
			switch msgp.UnsafeString(field) {
			case "Name":
				(*z)[zb0001].Name, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, zb0001, "Name")
					return
				}
			case "Value":
				(*z)[zb0001].Value, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, zb0001, "Value")
					return
				}
			default:
				bts, err = msgp.Skip(bts)
				if err != nil {
					err = msgp.WrapError(err, zb0001)
					return
				}
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Headers) Msgsize() (s int) {
	s = msgp.ArrayHeaderSize
	for zb0004 := range z {
		s += 1 + 5 + msgp.StringPrefixSize + len(z[zb0004].Name) + 6 + msgp.StringPrefixSize + len(z[zb0004].Value)
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Mail) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Envelope":
			err = z.Envelope.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Envelope")
				return
			}
		case "Content":
			err = z.Content.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Content")
				return
			}
		case "Trace":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Trace")
				return
			}
			if cap(z.Trace) >= int(zb0002) {
				z.Trace = (z.Trace)[:zb0002]
			} else {
				z.Trace = make([]TraceField, zb0002)
			}
			for za0001 := range z.Trace {
				err = z.Trace[za0001].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Trace", za0001)
					return
				}
			}
		case "ReceivedAt":
			z.ReceivedAt, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "ReceivedAt")
				return
			}
		case "ID":
			z.ID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Mail) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 5
	// write "Envelope"
	err = en.Append(0x85, 0xa8, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65)
	if err != nil {
		return
	}
	err = z.Envelope.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Envelope")
		return
	}
	// write "Content"
	err = en.Append(0xa7, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = z.Content.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Content")
		return
	}
	// write "Trace"
	err = en.Append(0xa5, 0x54, 0x72, 0x61, 0x63, 0x65)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Trace)))
	if err != nil {
		err = msgp.WrapError(err, "Trace")
		return
	}
	for za0001 := range z.Trace {
		err = z.Trace[za0001].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Trace", za0001)
			return
		}
	}
	// write "ReceivedAt"
	err = en.Append(0xaa, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x41, 0x74)
	if err != nil {
		return
	}
	err = en.WriteTime(z.ReceivedAt)
	if err != nil {
		err = msgp.WrapError(err, "ReceivedAt")
		return
	}
	// write "ID"
	err = en.Append(0xa2, 0x49, 0x44)
	if err != nil {
		return
	}
	err = en.WriteString(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Mail) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	// string "Envelope"
	o = append(o, 0x85, 0xa8, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65)
	o, err = z.Envelope.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Envelope")
		return
	}
	// string "Content"
	o = append(o, 0xa7, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74)
	o, err = z.Content.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Content")
		return
	}
	// string "Trace"
	o = append(o, 0xa5, 0x54, 0x72, 0x61, 0x63, 0x65)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Trace)))
	for za0001 := range z.Trace {
		o, err = z.Trace[za0001].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Trace", za0001)
			return
		}
	}
	// string "ReceivedAt"
	o = append(o, 0xaa, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x41, 0x74)
	o = msgp.AppendTime(o, z.ReceivedAt)
	// string "ID"
	o = append(o, 0xa2, 0x49, 0x44)
	o = msgp.AppendString(o, z.ID)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Mail) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Envelope":
			bts, err = z.Envelope.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Envelope")
				return
			}
		case "Content":
			bts, err = z.Content.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Content")
				return
			}
		case "Trace":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Trace")
				return
			}
			if cap(z.Trace) >= int(zb0002) {
				z.Trace = (z.Trace)[:zb0002]
			} else {
				z.Trace = make([]TraceField, zb0002)
			}
			for za0001 := range z.Trace {
				bts, err = z.Trace[za0001].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Trace", za0001)
					return
				}
			}
		case "ReceivedAt":
			z.ReceivedAt, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ReceivedAt")
				return
			}
		case "ID":
			z.ID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Mail) Msgsize() (s int) {
	s = 1 + 9 + z.Envelope.Msgsize() + 8 + z.Content.Msgsize() + 6 + msgp.ArrayHeaderSize
	for za0001 := range z.Trace {
		s += z.Trace[za0001].Msgsize()
	}
	s += 11 + msgp.TimeSize + 3 + msgp.StringPrefixSize + len(z.ID)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *MailboxAddress) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "LocalPart":
			z.LocalPart, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "LocalPart")
				return
			}
		case "Domain":
			z.Domain, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Domain")
				return
			}
		case "DisplayName":
			z.DisplayName, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "DisplayName")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z MailboxAddress) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "LocalPart"
	err = en.Append(0x83, 0xa9, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.LocalPart)
	if err != nil {
		err = msgp.WrapError(err, "LocalPart")
		return
	}
	// write "Domain"
	err = en.Append(0xa6, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.Domain)
	if err != nil {
		err = msgp.WrapError(err, "Domain")
		return
	}
	// write "DisplayName"
	err = en.Append(0xab, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.DisplayName)
	if err != nil {
		err = msgp.WrapError(err, "DisplayName")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z MailboxAddress) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "LocalPart"
	o = append(o, 0x83, 0xa9, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x74)
	o = msgp.AppendString(o, z.LocalPart)
	// string "Domain"
	o = append(o, 0xa6, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e)
	o = msgp.AppendString(o, z.Domain)
	// string "DisplayName"
	o = append(o, 0xab, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.DisplayName)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *MailboxAddress) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "LocalPart":
			z.LocalPart, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LocalPart")
				return
			}
		case "Domain":
			z.Domain, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Domain")
				return
			}
		case "DisplayName":
			z.DisplayName, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DisplayName")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z MailboxAddress) Msgsize() (s int) {
	s = 1 + 10 + msgp.StringPrefixSize + len(z.LocalPart) + 7 + msgp.StringPrefixSize + len(z.Domain) + 12 + msgp.StringPrefixSize + len(z.DisplayName)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Path) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Mailbox":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Mailbox")
				return
			}
			for zb0002 > 0 {
				zb0002--
				field, err = dc.ReadMapKeyPtr()
				if err != nil {
					err = msgp.WrapError(err, "Mailbox")
					return
				}
				switch msgp.UnsafeString(field) {
				case "LocalPart":
					z.Mailbox.LocalPart, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Mailbox", "LocalPart")
						return
					}
				case "Domain":
					z.Mailbox.Domain, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Mailbox", "Domain")
						return
					}
				case "DisplayName":
					z.Mailbox.DisplayName, err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Mailbox", "DisplayName")
						return
					}
				default:
					err = dc.Skip()
					if err != nil {
						err = msgp.WrapError(err, "Mailbox")
						return
					}
				}
			}
		case "SourceRoutes":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "SourceRoutes")
				return
			}
			if cap(z.SourceRoutes) >= int(zb0003) {
				z.SourceRoutes = (z.SourceRoutes)[:zb0003]
			} else {
				z.SourceRoutes = make([]string, zb0003)
			}
			for za0001 := range z.SourceRoutes {
				z.SourceRoutes[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "SourceRoutes", za0001)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Path) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "Mailbox"
	err = en.Append(0x82, 0xa7, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78)
	if err != nil {
		return
	}
	// map header, size 3
	// write "LocalPart"
	err = en.Append(0x83, 0xa9, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Mailbox.LocalPart)
	if err != nil {
		err = msgp.WrapError(err, "Mailbox", "LocalPart")
		return
	}
	// write "Domain"
	err = en.Append(0xa6, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.Mailbox.Domain)
	if err != nil {
		err = msgp.WrapError(err, "Mailbox", "Domain")
		return
	}
	// write "DisplayName"
	err = en.Append(0xab, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Mailbox.DisplayName)
	if err != nil {
		err = msgp.WrapError(err, "Mailbox", "DisplayName")
		return
	}
	// write "SourceRoutes"
	err = en.Append(0xac, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.SourceRoutes)))
	if err != nil {
		err = msgp.WrapError(err, "SourceRoutes")
		return
	}
	for za0001 := range z.SourceRoutes {
		err = en.WriteString(z.SourceRoutes[za0001])
		if err != nil {
			err = msgp.WrapError(err, "SourceRoutes", za0001)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Path) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "Mailbox"
	o = append(o, 0x82, 0xa7, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78)
	// map header, size 3
	// string "LocalPart"
	o = append(o, 0x83, 0xa9, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x74)
	o = msgp.AppendString(o, z.Mailbox.LocalPart)
	// string "Domain"
	o = append(o, 0xa6, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e)
	o = msgp.AppendString(o, z.Mailbox.Domain)
	// string "DisplayName"
	o = append(o, 0xab, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.Mailbox.DisplayName)
	// string "SourceRoutes"
	o = append(o, 0xac, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.SourceRoutes)))
	for za0001 := range z.SourceRoutes {
		o = msgp.AppendString(o, z.SourceRoutes[za0001])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Path) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Mailbox":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Mailbox")
				return
			}
			for zb0002 > 0 {
				zb0002--
				field, bts, err = msgp.ReadMapKeyZC(bts)
				if err != nil {
					err = msgp.WrapError(err, "Mailbox")
					return
				}
				switch msgp.UnsafeString(field) {
				case "LocalPart":
					z.Mailbox.LocalPart, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Mailbox", "LocalPart")
						return
					}
				case "Domain":
					z.Mailbox.Domain, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Mailbox", "Domain")
						return
					}
				case "DisplayName":
					z.Mailbox.DisplayName, bts, err = msgp.ReadStringBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "Mailbox", "DisplayName")
						return
					}
				default:
					bts, err = msgp.Skip(bts)
					if err != nil {
						err = msgp.WrapError(err, "Mailbox")
						return
					}
				}
			}
		case "SourceRoutes":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SourceRoutes")
				return
			}
			if cap(z.SourceRoutes) >= int(zb0003) {
				z.SourceRoutes = (z.SourceRoutes)[:zb0003]
			} else {
				z.SourceRoutes = make([]string, zb0003)
			}
			for za0001 := range z.SourceRoutes {
				z.SourceRoutes[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "SourceRoutes", za0001)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Path) Msgsize() (s int) {
	s = 1 + 8 + 1 + 10 + msgp.StringPrefixSize + len(z.Mailbox.LocalPart) + 7 + msgp.StringPrefixSize + len(z.Mailbox.Domain) + 12 + msgp.StringPrefixSize + len(z.Mailbox.DisplayName) + 13 + msgp.ArrayHeaderSize
	for za0001 := range z.SourceRoutes {
		s += msgp.StringPrefixSize + len(z.SourceRoutes[za0001])
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Recipient) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Address":
			err = z.Address.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Address")
				return
			}
		case "DSNParams":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "DSNParams")
					return
				}
				z.DSNParams = nil
			} else {
				if z.DSNParams == nil {
					z.DSNParams = new(DSNRecipientParams)
				}
				var zb0002 uint32
				zb0002, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "DSNParams")
					return
				}
				for zb0002 > 0 {
					zb0002--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "DSNParams")
						return
					}
					switch msgp.UnsafeString(field) {
					case "Notify":
						var zb0003 uint32
						zb0003, err = dc.ReadArrayHeader()
						if err != nil {
							err = msgp.WrapError(err, "DSNParams", "Notify")
							return
						}
						if cap(z.DSNParams.Notify) >= int(zb0003) {
							z.DSNParams.Notify = (z.DSNParams.Notify)[:zb0003]
						} else {
							z.DSNParams.Notify = make([]string, zb0003)
						}
						for za0001 := range z.DSNParams.Notify {
							z.DSNParams.Notify[za0001], err = dc.ReadString()
							if err != nil {
								err = msgp.WrapError(err, "DSNParams", "Notify", za0001)
								return
							}
						}
					case "ORcpt":
						z.DSNParams.ORcpt, err = dc.ReadString()
						if err != nil {
							err = msgp.WrapError(err, "DSNParams", "ORcpt")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "DSNParams")
							return
						}
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Recipient) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "Address"
	err = en.Append(0x82, 0xa7, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73)
	if err != nil {
		return
	}
	err = z.Address.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Address")
		return
	}
	// write "DSNParams"
	err = en.Append(0xa9, 0x44, 0x53, 0x4e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73)
	if err != nil {
		return
	}
	if z.DSNParams == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		// map header, size 2
		// write "Notify"
		err = en.Append(0x82, 0xa6, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79)
		if err != nil {
			return
		}
		err = en.WriteArrayHeader(uint32(len(z.DSNParams.Notify)))
		if err != nil {
			err = msgp.WrapError(err, "DSNParams", "Notify")
			return
		}
		for za0001 := range z.DSNParams.Notify {
			err = en.WriteString(z.DSNParams.Notify[za0001])
			if err != nil {
				err = msgp.WrapError(err, "DSNParams", "Notify", za0001)
				return
			}
		}
		// write "ORcpt"
		err = en.Append(0xa5, 0x4f, 0x52, 0x63, 0x70, 0x74)
		if err != nil {
			return
		}
		err = en.WriteString(z.DSNParams.ORcpt)
		if err != nil {
			err = msgp.WrapError(err, "DSNParams", "ORcpt")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Recipient) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "Address"
	o = append(o, 0x82, 0xa7, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73)
	o, err = z.Address.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Address")
		return
	}
	// string "DSNParams"
	o = append(o, 0xa9, 0x44, 0x53, 0x4e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73)
	if z.DSNParams == nil {
		o = msgp.AppendNil(o)
	} else {
		// map header, size 2
		// string "Notify"
		o = append(o, 0x82, 0xa6, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79)
		o = msgp.AppendArrayHeader(o, uint32(len(z.DSNParams.Notify)))
		for za0001 := range z.DSNParams.Notify {
			o = msgp.AppendString(o, z.DSNParams.Notify[za0001])
		}
		// string "ORcpt"
		o = append(o, 0xa5, 0x4f, 0x52, 0x63, 0x70, 0x74)
		o = msgp.AppendString(o, z.DSNParams.ORcpt)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Recipient) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Address":
			bts, err = z.Address.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Address")
				return
			}
		case "DSNParams":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.DSNParams = nil
			} else {
				if z.DSNParams == nil {
					z.DSNParams = new(DSNRecipientParams)
				}
				var zb0002 uint32
				zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "DSNParams")
					return
				}
				for zb0002 > 0 {
					zb0002--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "DSNParams")
						return
					}
					switch msgp.UnsafeString(field) {
					case "Notify":
						var zb0003 uint32
						zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "DSNParams", "Notify")
							return
						}
						if cap(z.DSNParams.Notify) >= int(zb0003) {
							z.DSNParams.Notify = (z.DSNParams.Notify)[:zb0003]
						} else {
							z.DSNParams.Notify = make([]string, zb0003)
						}
						for za0001 := range z.DSNParams.Notify {
							z.DSNParams.Notify[za0001], bts, err = msgp.ReadStringBytes(bts)
							if err != nil {
								err = msgp.WrapError(err, "DSNParams", "Notify", za0001)
								return
							}
						}
					case "ORcpt":
						z.DSNParams.ORcpt, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "DSNParams", "ORcpt")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "DSNParams")
							return
						}
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Recipient) Msgsize() (s int) {
	s = 1 + 8 + z.Address.Msgsize() + 10
	if z.DSNParams == nil {
		s += msgp.NilSize
	} else {
		s += 1 + 7 + msgp.ArrayHeaderSize
		for za0001 := range z.DSNParams.Notify {
			s += msgp.StringPrefixSize + len(z.DSNParams.Notify[za0001])
		}
		s += 6 + msgp.StringPrefixSize + len(z.DSNParams.ORcpt)
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *TraceField) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Type":
			z.Type, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Type")
				return
			}
		case "FromDomain":
			z.FromDomain, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "FromDomain")
				return
			}
		case "FromIP":
			z.FromIP, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "FromIP")
				return
			}
		case "ByDomain":
			z.ByDomain, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ByDomain")
				return
			}
		case "Via":
			z.Via, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Via")
				return
			}
		case "With":
			z.With, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "With")
				return
			}
		case "ID":
			z.ID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "For":
			z.For, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "For")
				return
			}
		case "Timestamp":
			z.Timestamp, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "Timestamp")
				return
			}
		case "TLS":
			z.TLS, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "TLS")
				return
			}
		case "Raw":
			z.Raw, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Raw")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *TraceField) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 11
	// write "Type"
	err = en.Append(0x8b, 0xa4, 0x54, 0x79, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Type)
	if err != nil {
		err = msgp.WrapError(err, "Type")
		return
	}
	// write "FromDomain"
	err = en.Append(0xaa, 0x46, 0x72, 0x6f, 0x6d, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.FromDomain)
	if err != nil {
		err = msgp.WrapError(err, "FromDomain")
		return
	}
	// write "FromIP"
	err = en.Append(0xa6, 0x46, 0x72, 0x6f, 0x6d, 0x49, 0x50)
	if err != nil {
		return
	}
	err = en.WriteString(z.FromIP)
	if err != nil {
		err = msgp.WrapError(err, "FromIP")
		return
	}
	// write "ByDomain"
	err = en.Append(0xa8, 0x42, 0x79, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.ByDomain)
	if err != nil {
		err = msgp.WrapError(err, "ByDomain")
		return
	}
	// write "Via"
	err = en.Append(0xa3, 0x56, 0x69, 0x61)
	if err != nil {
		return
	}
	err = en.WriteString(z.Via)
	if err != nil {
		err = msgp.WrapError(err, "Via")
		return
	}
	// write "With"
	err = en.Append(0xa4, 0x57, 0x69, 0x74, 0x68)
	if err != nil {
		return
	}
	err = en.WriteString(z.With)
	if err != nil {
		err = msgp.WrapError(err, "With")
		return
	}
	// write "ID"
	err = en.Append(0xa2, 0x49, 0x44)
	if err != nil {
		return
	}
	err = en.WriteString(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "For"
	err = en.Append(0xa3, 0x46, 0x6f, 0x72)
	if err != nil {
		return
	}
	err = en.WriteString(z.For)
	if err != nil {
		err = msgp.WrapError(err, "For")
		return
	}
	// write "Timestamp"
	err = en.Append(0xa9, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70)
	if err != nil {
		return
	}
	err = en.WriteTime(z.Timestamp)
	if err != nil {
		err = msgp.WrapError(err, "Timestamp")
		return
	}
	// write "TLS"
	err = en.Append(0xa3, 0x54, 0x4c, 0x53)
	if err != nil {
		return
	}
	err = en.WriteBool(z.TLS)
	if err != nil {
		err = msgp.WrapError(err, "TLS")
		return
	}
	// write "Raw"
	err = en.Append(0xa3, 0x52, 0x61, 0x77)
	if err != nil {
		return
	}
	err = en.WriteString(z.Raw)
	if err != nil {
		err = msgp.WrapError(err, "Raw")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *TraceField) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 11
	// string "Type"
	o = append(o, 0x8b, 0xa4, 0x54, 0x79, 0x70, 0x65)
	o = msgp.AppendString(o, z.Type)
	// string "FromDomain"
	o = append(o, 0xaa, 0x46, 0x72, 0x6f, 0x6d, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e)
	o = msgp.AppendString(o, z.FromDomain)
	// string "FromIP"
	o = append(o, 0xa6, 0x46, 0x72, 0x6f, 0x6d, 0x49, 0x50)
	o = msgp.AppendString(o, z.FromIP)
	// string "ByDomain"
	o = append(o, 0xa8, 0x42, 0x79, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e)
	o = msgp.AppendString(o, z.ByDomain)
	// string "Via"
	o = append(o, 0xa3, 0x56, 0x69, 0x61)
	o = msgp.AppendString(o, z.Via)
	// string "With"
	o = append(o, 0xa4, 0x57, 0x69, 0x74, 0x68)
	o = msgp.AppendString(o, z.With)
	// string "ID"
	o = append(o, 0xa2, 0x49, 0x44)
	o = msgp.AppendString(o, z.ID)
	// string "For"
	o = append(o, 0xa3, 0x46, 0x6f, 0x72)
	o = msgp.AppendString(o, z.For)
	// string "Timestamp"
	o = append(o, 0xa9, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70)
	o = msgp.AppendTime(o, z.Timestamp)
	// string "TLS"
	o = append(o, 0xa3, 0x54, 0x4c, 0x53)
	o = msgp.AppendBool(o, z.TLS)
	// string "Raw"
	o = append(o, 0xa3, 0x52, 0x61, 0x77)
	o = msgp.AppendString(o, z.Raw)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *TraceField) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Type":
			z.Type, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Type")
				return
			}
		case "FromDomain":
			z.FromDomain, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "FromDomain")
				return
			}
		case "FromIP":
			z.FromIP, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "FromIP")
				return
			}
		case "ByDomain":
			z.ByDomain, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ByDomain")
				return
			}
		case "Via":
			z.Via, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Via")
				return
			}
		case "With":
			z.With, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "With")
				return
			}
		case "ID":
			z.ID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "For":
			z.For, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "For")
				return
			}
		case "Timestamp":
			z.Timestamp, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Timestamp")
				return
			}
		case "TLS":
			z.TLS, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TLS")
				return
			}
		case "Raw":
			z.Raw, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Raw")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *TraceField) Msgsize() (s int) {
	s = 1 + 5 + msgp.StringPrefixSize + len(z.Type) + 11 + msgp.StringPrefixSize + len(z.FromDomain) + 7 + msgp.StringPrefixSize + len(z.FromIP) + 9 + msgp.StringPrefixSize + len(z.ByDomain) + 4 + msgp.StringPrefixSize + len(z.Via) + 5 + msgp.StringPrefixSize + len(z.With) + 3 + msgp.StringPrefixSize + len(z.ID) + 4 + msgp.StringPrefixSize + len(z.For) + 10 + msgp.TimeSize + 4 + msgp.BoolSize + 4 + msgp.StringPrefixSize + len(z.Raw)
	return
}
